name: speedclimbing
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audioplayers: ^5.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_slidable: ^3.0.0
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.0
  riverpod_annotation: ^2.1.1
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^22.2.8

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.2.5
  riverpod_lint: ^2.0.0

dependency_overrides:
  analyzer: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/880.wav
    - assets/1760.wav
